### ISSUE TITLE
Dont work npm command: npm install ccnet2

### ISSUE THREAD

**Issue by lampaa** [devoll/ccnet2#1]
Hi!
I tried install plugin from npm repo and received an error:

npm ERR! 404 Not Found: ccnet2
npm ERR! 404
npm ERR! 404 'ccnet2' is not in the npm registry.

**Comment by devoll** [comment]
Hi!
I'm sorry for this fail, but I never publish this project to npm and forgot about it. I've fixed and published project to npm. Please, be carefully to use this module because it's first version.
